In [17]:
#!pip install opencv-python
#import cv2 #library import

In [18]:
#!pip install imutils

In [19]:
import cv2  #image
import time  #delay
import imutils #resize
import numpy 


In [20]:
img=cv2.imread("sample_image.png")

In [21]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [11]:
grayimg=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)   #color to gray image
cv2.imwrite("grayimg.jpg",grayimg)   #save an image
cv2.imshow("Orig",img)
cv2.imshow("Gray",grayimg)

In [25]:
import cv2
import imutils
import os

# File path
file_path = 'sample_image.png'

# Check if file exists
if not os.path.exists(file_path):
    print(f"Error: File '{file_path}' does not exist.")
else:
    # Load the image
    img = cv2.imread(file_path)

    # Check if image is loaded successfully
    if img is None:
        print("Error: Could not load image. Unsupported file format or path issue.")
    else:
        # Resize the image
        resizedImg = imutils.resize(img, width=500)
        cv2.imwrite('resizedImage.jpg', resizedImg)
        print("Image resized and saved successfully.")


Image resized and saved successfully.


In [26]:
resizedImg = imutils.resize(img, width=500)
cv2.imwrite('resizedImage.jpg', resizedImg)
True

True

alg = "haarcascade_frontalface_default.xml" #accessed the model file
haar_cascade = cv2.CascadeClassifier(alg) #loading the model wth cv2
cam = cv2.VideoCapture(0) #initializing camera

In [30]:
#import cv2

# Initialize the camera
cam = cv2.VideoCapture(0)  # Use 0 for the default camera or replace with the camera index

# Load the Haar cascade file for face detection
haar_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

if not cam.isOpened():
    print("Error: Could not access the camera.")
    exit()

while True:
    # Read the frame from the camera
    ret, img = cam.read()
    if not ret:
        print("Error: Could not read frame.")
        break

    # Convert the frame to grayscale
    grayImg = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Detect faces in the frame
    faces = haar_cascade.detectMultiScale(grayImg, scaleFactor=1.3, minNeighbors=4)

    # Draw rectangles around detected faces
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)

    # Show the frame with detected faces
    cv2.imshow("Face Detection", img)

    # Break the loop if the 'Esc' key is pressed
    key = cv2.waitKey(10)
    if key == 27:  # 27 is the ASCII code for the 'Esc' key
        break

# Release the camera and close all OpenCV windows
cam.release()
cv2.destroyAllWindows()